#+TITLE: EEP153 Syllabus & Materials
#+AUTHOR: Ethan Ligon
#+EMAIL: ligon@berkeley.edu
#+DATE: Spring 2021

* Overview
This course takes a quantitative, hands-on
approach to understanding the challenges of
feeding the human population of the planet
Earth.  We'll discuss topics of nutrition,
subsistence food consumption, and consumer
demand for food to develop our
understanding of the current situation.
We'll then develop both theories and
computer models of population dynamics
taking into account people's decisions
about child-bearing, changes in mortality,
and changes in food supply in order to
learn something about the future of food.
Focus throughout the course will be on
developing practical tools to work with
real-world data.  Those tools will include
linear programs, globally regular demand
systems, and a variety of
econometric tools.  The course will rely on
a knowledge of the programming language
=python=.
* Administrivia

** Evaluation (Grading)
   Grading in course depends primarily on /peer evaluation/.  In
   particular, every project will lead to you evaluating your
   classmates in two main ways, and being evaluated yourself in three.

*** Team evaluations
    Everyone will evaluate every team according to several criteria:
**** Code
     1. Did code work as intended?
     2. How elegant was the teams' code?
     3. How ambitious were design goals?
     4. How completely were design goals met?
**** Organization
     In the presentation:
     1. How well did team manage its time?
     2. How well did the team work together?
**** Style
     1. How interesting was the presentation?
     2. How polished was the presentation?
**** Overall
     1. If you were in the position of needing to hire a team to do
        population analysis, would you hire this team?
     2. Other constructive comments & criticisms.
**** Ranking
     Finally, we'll ask you to rank all teams according to your overall
     impression of their presentation.

*** Teammate evaluations
    Everyone will also evaluate all of the individuals on their team
    according to several criteria:
    1. Quality of work
    2. Could be counted on to complete tasks in a timely fashion?
    3. Helpful to others win group?
    4. Contributed to the smooth working of the team?

    In addition, we'll ask you to give some additional information
    about each of your teammates, indicating:
    - What were each person's main strengths?
    - Would you like to work with this person again?

    And finally, we'll ask you to:
    - Rank each person according to their overall contribution to the project.

*** Quality of evaluation
    Your own evaluations are an important individual contribution to
    the class, and the quality of your evaluations will affect your
    grade.  There are three criteria we'll use in judging the quality
    of your evaluations.
**** Prediction of others' evaluations of you
     You'll provide evaluations not only of *other* teams, but also of
     your own team.  And you'll evaluate not just your teammates'
     contribution to the project, but also your *own* contribution.

     Your self-evaluations will affect your grade.  However, the /way/
     in which these will affect your grade will depend *not* on how
     good you say you are, but how accurately you *predict* how others
     evaluate you.  In particular, the closer your guesses about
     others' evaluations are to the /average/ of what others give you
     the higher your grade.
**** Information in your own evaluations of others
     The greater the information provided by your evaluations of others
     the higher your grade.  The amount of information will be measured
     partly according to the variation of your evaluation of others, and
     partly according to a (subjective) measure of the quality of your
     comments.

     Observation: if you give everyone the /same/ scores (e.g.,
     everyone gets top score) there is /no/ variation in your
     evaluation.  This would negatively affect your own grade.
**** Correlation with evaluations of others
     Your evaluations must be honest, in the sense that they are
     attempts to fairly evaluate the efforts of others and of your own
     efforts.  Ideally there will be broad agreement across different
     people's evaluations.  If your evaluations are `outliers' then
     this will /negatively/ effect your grade.  Further, if upon
     examination it appears that you've used your evaluations
     strategically there may be further repercussions, most
     particularly if the manner in which you've evaluated others
     violates Berkeley's Honor Code (i.e., you must "act with
     integrity, honesty, and respect for others").


* Projects
   The course revolves around a sequence of
   topics, each exploring a substantive
   issue involved in "feeding the planet"
   and each introducing novel tools.
   Students will work in small groups to
   complete one structured project for each
   topic.

** Introduction & Collaboration
** Population and Food Supply
** Subsistence Diets
** Consumer Food Demand
** Hacking for Nutrition

