#+TITLE: EEP153 Syllabus & Materials
#+AUTHOR: Ethan Ligon
#+EMAIL: ligon@berkeley.edu
#+DATE: Spring 2025

* Overview
This course takes a quantitative, hands-on
approach to understanding the challenges of
feeding the human population of the planet
Earth.  We'll discuss topics of nutrition,
subsistence food consumption, and consumer
demand for food to develop our
understanding of the current situation.
We'll then develop both theories and
computer models of population dynamics
taking into account people's decisions
about child-bearing, changes in mortality,
and changes in food supply in order to
learn something about the future of food.
Focus throughout the course will be on
developing practical tools to work with
real-world data.  Those tools will include
linear programs, globally regular demand
systems, and a variety of
econometric tools.  The course will rely on
a knowledge of the programming language
=python=.
* Administrivia
** Prerequisites 
   Data8, EEP100 or
   equivalents required; Math 54
   recommended.

** Schedule
   Meet two times per week; Tuesdays and Thursdays 10am--12pm (Pacific Time).
   
   We'll have a mix of lectures and discussion (typically on Tuesdays)
   and tutorials and group work (typically on Thursdays).

  We'll meet in person in Social Sciences 110.   Office hours may be in person or virtual.

** People
   - Instructor :: Ethan Ligon (ligon@berkeley.edu)
   - GSI :: Scott Kjorlien (scottkjorlien@berkeley.edu)
   - Tutor :: Faye Fang (ce_fang@berkeley.edu)

*** Office Hours/Individual Assistance
    - Questions/Discussion :: Please use [[https://edstem.org]] to ask questions of
      the instructor or assistants; we're likely to miss email.  Note
      that you can post anonymously and/or privately.

    - Instructor's Office Hours :: You may also make an appointment to
      speak with Professor Ligon during his office hours via
      https://are.berkeley.edu/~ligon/appointment.html.

    - Office hours (GSI) :: Scott will hold an office hour Thursdays 1--2p in Giannini 203, or by appointment.

** Evaluation (Grading)
   Grading in course depends primarily on /peer evaluation/.  In
   particular, every project will lead to you evaluating your
   classmates in two main ways, and being evaluated yourself in three.

*** Team evaluations
    Everyone will evaluate every team according to several criteria.  For example,
**** Code
     1. Did code work as intended?
     2. How elegant was the team's code?
     3. How ambitious were design goals?
     4. How completely were design goals met?
**** Organization
     In the presentation:
     1. How well did team manage its time?
     2. How well did the team work together?
**** Style
     1. How interesting was the presentation?
     2. How polished was the presentation?
**** Overall
     1. If you were in the position of needing to hire a team to do
        this sort of analysis, would you hire this team?
     2. Other constructive comments & criticisms.
     3. Finally, we'll ask you to rank all teams according to your overall
     impression of their presentation.

*** Teammate evaluations
    Everyone will also evaluate all of the individuals on their team
    according to several criteria:
    1. Quality of work
    2. Could be counted on to complete tasks in a timely fashion?
    3. Helpful to others in group?
    4. Contributed to the smooth working of the team?

    In addition, we'll ask you to give some additional information
    about each of your teammates, indicating:
    - What were each person's main strengths?
    - Would you like to work with this person again?

    And finally, we'll ask you to:
    - Rank each person according to their overall contribution to the project.

*** Quality of evaluation
    Your own evaluations are an important individual contribution to
    the class, and the quality of your evaluations will affect your
    grade.  There are three criteria we'll use in judging the quality
    of your evaluations.
**** Prediction of others' evaluations of you
     You'll provide evaluations not only of *other* teams, but also of
     your own team.  And you'll evaluate not just your teammates'
     contribution to the project, but also your *own* contribution.

     Your self-evaluations will affect your grade.  However, the /way/
     in which these will affect your grade will depend *not* on how
     good you say you are, but how accurately you *predict* how others
     evaluate you.  In particular, the closer your guesses about
     others' evaluations are to the /average/ of what others give you
     the higher your grade.
**** Information in your own evaluations of others
     The greater the information provided by your evaluations of others
     the higher your grade.  The amount of information will be measured
     partly according to the variation of your evaluation of others, and
     partly according to a (subjective) measure of the quality of your
     comments.

     Observation: if you give everyone the /same/ scores (e.g.,
     everyone gets top score) there is /no/ variation in your
     evaluation.  This would negatively affect your own grade.
**** Correlation with evaluations of others
     Your evaluations must be honest, in the sense that they are
     attempts to fairly evaluate the efforts of others and of your own
     efforts.  Ideally there will be broad agreement across different
     people's evaluations.  If your evaluations are `outliers' then
     this may /negatively/ effect your grade.  Further, if upon
     examination it appears that you've used your evaluations
     strategically there may be further repercussions, most
     particularly if the manner in which you've evaluated others
     violates Berkeley's Honor Code (i.e., you must "act with
     integrity, honesty, and respect for others").
*** Instructors' Evaluation
For each project, you will also be evaluated in terms of your /engagement/.  This is the one category which will be evaluated solely by instructors and GSIs, rather than by your peers.  Particular things we will look at:
 - Number and quality of comments, etc. on [[https://edstem.org][edstem.org]].
 - Number and quality  of comments and issues on github repositories (both yours and others).
 - Number and quality of comments or PRs specifically pertaining to issues/bugs in code or material in EEP153 repos, including
   - https://github.com/ligonteaching/EEP153_Materials/issues
   - https://github.com/ligonteaching/EEP153_Exercises/issues
   - https://github.com/ligon/Population
   - https://github.com/ligon/MinCostDiet
   - https://github.com/ligon/FoodDemand
   - https://github.com/ligon/HackingFood

* Projects
   The course revolves around a sequence of
   topics, each exploring a substantive
   issue involved in "feeding the planet"
   and each introducing novel tools.
   Students will work in small groups to
   complete one structured project for each
   topic.
** Introduction & Collaboration
Students will review introductory materials about coding 
(Python and Pandas) and potential ways to collaborate 
(Git, Google Colab, Trello, and Agile). See online posts
for links to resources.

** Population & Food Supply
   Students will construct datasets on the
   distribution of characteristics in the
   world population, including measures of
   resources, and the age and sex
   composition of the world population.  A
   separate dataset allows us to think
   about food supply.
*** Readings
    - Malthus [[https://oll.libertyfund.org/titles/malthus-an-essay-on-the-principle-of-population-1798-1st-ed#lf0195_head_002][An Essay of the Principle of Population (1798)]]
    - de Janvry-Sadoulet (2015), [[https://github.com/ligonteaching/EEP153_Materials/blob/master/Project1/Chapter_11_Population15.pdf][Chapter 11 of Development Economics]]
    - Fuglie (2012), https://www.ers.usda.gov/amber-waves/2012/september/global-agriculture/
    - NYTimes "What to eat on a burning planet" series, especially:
      - https://www.nytimes.com/2024/07/28/opinion/food-climate-crisis-prices.html
      - https://www.nytimes.com/2024/12/13/opinion/food-agriculture-factory-farms-climate-change.html

*** Empirical exercise: Population pyramids                        :noexport:
    - Deaton (1997)
    - https://github.com/afolaborn/Python_Jupyter_Notebook/blob/master/Population-Pyramid/Population_Pyramid_Final.ipynb

** Subsistence Diets
   Every living human has some minimal, or subsistence, nutritional
   requirements; should these not be satisfied health and even life
   may be threatened.  People satisfy these needs by eating various
   kinds of food, but there may be many different food diets which
   satisfy people's subsistence requirements.  One criterion for
   choosing among these diets is /cost/. 

   In this topic students use contemporary data on different kinds of
   foods available to the US population along with prices to
   construct estimates of /minimum cost/ subsistence diets.  
*** Readings
    - [[https://github.com/ligonteaching/EEP153_Materials/blob/master/Project2/stigler45.pdf][Stigler (1945) "The Cost of Subsistence"]]
    - [[https://github.com/ligonteaching/EEP153_Materials/blob/master/Project2/dantzig90.pdf][Dantzig (1990) "The Diet Problem"]]


*** Other resources                                                :noexport:
    :PROPERTIES:
    :ID:       3c8197f3-98f8-4fe8-a8a6-383c671bb77a
    :END:
    - [[http://www.jstor.org/stable/pdf/25061369.pdf][Dantzig (1990)]]
    - [[https://pubsonline.informs.org/doi/pdf/10.1287/opre.49.1.1.11187][Stigler's Diet Problem Revisited]]
*** Computational exercise: Subsistence food needs                 :noexport:
    Recapitulation of \cite{stigler45}; linear programming.  For an
    individual with characteristics $z$ facing prices $p$ obtain
    subsistence cost function $\phi(p;z)$. 

    Need data on:
    - Possible foods & food-nutrient conversion ::
      Note that USDA dataset uses "NDB" codes to identify different
      kinds of foods; can also map NDB -> UPC for many (mostly processed) foods.
      - https://ndb.nal.usda.gov/ndb/search/list;
      - here's documentation of the api: https://ndb.nal.usda.gov/ndb/doc/index
      - Here's the actual data:
        https://www.ars.usda.gov/northeast-area/beltsville-md/beltsville-human-nutrition-research-center/nutrient-data-laboratory/docs/sr28-download-files/

    - Food prices :: 
      - Safeway data?
      - Nielsen homescan panel?
      - CEX?
      - IRI 
      - USDA NCPP https://www.cnpp.usda.gov/data
      - USDA Quarterly Food-at-home price database
        https://www.ers.usda.gov/data-products/quarterly-food-at-home-price-database/
        Drawn from Nielsen HomeScan data; aggregated to one of 54
        "foodgroups".   
    - Nutritional requirements :: Both  recommended daily allowances
         (RDA) *plus* "tolerable upper intake levels". 
         https://ods.od.nih.gov/Health_Information/Dietary_Reference_Intakes.aspx
** Consumer Food Demand
   In practice, even very poor people seldom choose their diets on
   the basis of minimum costs.  Instead, people balance nutritional
   requirements against considerations of cost and what we might call
   the gastronomical value of different diets.  Here we explore the
   theory of demand as it pertains to these diets---how does demand
   for food depend on income, prices, and other observables?  How
   well (or poorly) do these diets serve nutritional ends?
*** Readings
    - Review basic demand theory (e.g., Chapters 3--5 in Nicholson-Snyder) 
*** Other Readings                                                 :noexport:
    - Dubois, Griffiths, Nevo
    - Atkin (2012)
*** Computational exercise: CFE demands with subsistence           :noexport:
*** Empirical exercise: Estimate demands in different populations  :noexport:
    How does demand depend on price?   On income?  On individual
    characteristics?  On "tastes"?
**** Data
     - Indian NSS
     - US CEX
     - US Nielsen HomeScan
*** Empirical exercise: Invert food demands to obtain nutrient demands :noexport:
    
** Estimating Food Demand Systems
   Students will use data on household food expenditures for
   populations from different countries to estimate systems of food
   demand, and relate these demands to the subsistence diets
   calculated in the earlier topic.

   With these results in hand you will construct aggregate
   demand functions that allow one to make predictions regarding how
   aggregate demand for different kinds of foods depends on the
   distribution of resources and the demographic composition of the
   global population. 
** Hacking Food & Nutrition

This project exploits our work on demand for food and is focused on
evaluating what kinds of *policies* might be effective at improving
nutritional outcomes for particular populations.  Our earlier work
addressed the question of how demand for different kinds of food
depends on prices, budgets, and household characteristics, taking as
given prices, budgets, and so on.

One of the take-aways from our earlier project is that the food people
/choose/ to eat may be quite different from the foods that people
/should/ eat, from a nutritional perspective.   

But if dietary choices respond to prices and budgets, it may be
possible to manipulate nutritional outcomes by changing either prices
or budgets.  We can assess the costs of this kind of manipulation
(e.g., the deadweight cost of a tax or subsidy); where these costs are
large we can also think about the value of innovation in either the
desirability or nutritional content of food.

*** Readings
    - Technical change: [[http://www.plantphysiol.org/content/124/2/487?ijkey=c12c5c79e5b11c10820b21877391b978804dc1c5&keytype2=tf_ipsecsha][Borlaug (2000)]], [[https://arstechnica.com/science/2019/06/why-havent-genetically-engineered-crops-made-food-better/][Ars Technica (2019)]]
    - Changes in budget: [[https://www.jstor.org/stable/40278509][Deaton-Dreze (2009)]]
    - Changes in relative prices: [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5024386/][Falbe et al (2016)]]
